### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 805: character maps to <undefined>

### ISSUE THREAD

**Issue by HatemAr** [Blazin64/movie-rating-prediction#1]
Hello, after I installed the necessary packages, I tried to run the program. I get these errors:
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\hatem\AppData\Local\Programs\Python\Python36\lib\tkinter\__init__.py", line 1699, in __call__
    return self.func(*args)
  File "C:/Users/hatem/PycharmProjects/DWProject/Project.py", line 67, in runner2
    self.finder(self.predictions, users)
  File "C:/Users/hatem/PycharmProjects/DWProject/Project.py", line 78, in finder
    movie_dict = self.get_movie_titles(movie_ids)
  File "C:/Users/hatem/PycharmProjects/DWProject/Project.py", line 179, in get_movie_titles
    for row in reader:
  File "C:\Users\hatem\AppData\Local\Programs\Python\Python36\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 805: character maps to <undefined>

**Comment by Blazin64** [comment]
**Note:** This project is not under active development right now. (It was only a class project.)

The error you encountered is a Windows-specific issue. Python's `open()` function usually expects CP-1252 encoded text on Windows, but your input data is likely using UTF-8 encoding. Theoretically, you may be able to fix this by adding the `encoding='utf8'` argument where the `open()` function is used.

In this case, you could try changing the code on line 176

```
with open('./ml-latest-small/movies.csv', "r") as csvfile:
```

to be

```
with open('./ml-latest-small/movies.csv', "r", encoding='utf8') as csvfile:
```

Although I currently cannot offer any further help, **_please_** do tell me if the modification I described fixes your problem.
